#!/bin/bash
set -eo pipefail

MODES="above|work|same|right|home|single"

_fail_no_mode() {
  echo "Error: must supply a mode as arg1 <$MODES>"
  exit 1
}

_fail_bad_mode() {
  echo "Error: invalid mode $1 (expected <$MODES>)"
  exit 1
}

_do_auto() {
  out="`xrandr --query --props`"
  single_test_sum="`xrandr | grep -F ' connected ' | md5sum | awk '{print $1}'`"
  echo "$out" | fgrep -q 00ffffffffffff0010acfb404c443141 && _main "work" "from_auto" && exit 0
  [[ "$single_test_sum" == "1cabd7be17c7fd2c54466895839932bc" ]] && _main "single" "from_auto" && exit 0
}

_main() {
  MODE=$1
  [[ "$MODE" == "" ]] && _fail_no_mode
  [[ "$2" == "from_auto" ]] && echo "Auto detected mode \"$MODE\""

  MAIN=eDP-1
  set +e
  OTHER=`xrandr | fgrep ' connected' | awk '{print $1}' | fgrep -v eDP-1 | head -n1`
  [[ "$OTHER" != "" ]] && xrandr --output $OTHER --auto
  set -e

  killall randy 2>/dev/null || true

  case $MODE in
  "above" | "work")
    xrandr --output $OTHER --above $MAIN
    /home/iphands/prog/randy/target/release/randy ~/prog/randy/config/my_laptop.yml &
    ;;
  "same" | "same-as")
    xrandr --output $OTHER --same-as $MAIN
    /home/iphands/prog/randy/target/release/randy ~/prog/randy/config/my_laptop.yml &
    ;;
  "home")
    xrandr --output $OTHER --right-of $MAIN
    xrandr --output $OTHER --pos 1920x-1080
    /home/iphands/prog/randy/target/release/randy ~/prog/randy/config/my_laptop_docked.yml &
    ;;
  "single")
    xrandr --auto
    xrandr --output $MAIN --auto
    /home/iphands/prog/randy/target/release/randy ~/prog/randy/config/my_laptop.yml &
    ;;

  *) _fail_bad_mode $MODE
  esac

  sleep 0.150
  fluxbox-remote restart
  sleep 0.150
  fbsetbg -c ~/Documents/tux.png
}

[[ "$1" == "" ]] && _do_auto $1
_main $1
