[package]
name = "dirchomp"
version = "0.1.0"
authors = ["Ian Hads <iphands@gmail.com>"]
edition = "2018"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'

[dependencies]
