#!/bin/bash
set -e
source ~/.config/my-rtl.sh
[[ "$RTL_BASE_FOLDER" == "" ]] && {
  echo "Could not find RTL_BASE_FOLDER in ~/.config/my-rtl.sh! Exiting"
  exit 1
}

FOLDER="$RTL_BASE_FOLDER/amr"
mkdir -p $FOLDER
echo "
FOLDER:  $FOLDER
"

set +e
while true
do
  for var in `seq 902.0 0.500 928.5`
  do
    ~/go/bin/rtlamr \
      -samplerate 2048k \
      -duration 30s \
      -centerfreq ${var}M 2>&1 | tee -a $FOLDER/test.${var}.log
  done
done
